var searchData=
[
  ['data_20types',['Data Types',['../group__data__types.html',1,'']]],
  ['datatype_20conversions',['Datatype Conversions',['../group__intr__cnv.html',1,'']]],
  ['direct_20digital_20synthesis_20_28dds_29_20interpolation',['Direct Digital Synthesis (DDS) Interpolation',['../group__intr__dds__ipol.html',1,'']]],
  ['digital_20pre_2ddistortion',['Digital Pre-Distortion',['../group__intr__dpd.html',1,'']]],
  ['datatype_20conversions',['Datatype Conversions',['../group__intr__gpvectorconv__conversions.html',1,'']]],
  ['delayed_20scalar_20moves',['Delayed Scalar Moves',['../group__intr__scldelay.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__16cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__16cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__16cx32__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__16cx32c__dcc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__16x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__16x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__32cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__32cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__32cx32__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__32cx32c__dcc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__32x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__32x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__16cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__antisym__16cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__16cx32__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__antisym__16cx32c__dcc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__antisym__16x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__antisym__16x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__32cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__antisym__32cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__32cx32__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__antisym__32cx32c__dcc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__antisym__32x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__antisym__32x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__ct__16cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__antisym__ct__16cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__ct__16cx32__dcn.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__antisym__ct__16x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__antisym__ct__16x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__ct__32cx16__dcn.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__ct__32cx32__dcn.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__antisym__ct__32x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__antisym__ct__32x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__uct__16cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__antisym__uct__16cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__antisym__uct__16cx32__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__antisym__uct__16cx32c__dcc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__cmp__16x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__cmp__16x32c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__cmp__32x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__cmp__32x32c__dnc.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__conj__antisym__32cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__conj__sym__32cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__16cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__sym__16cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__16cx32__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__sym__16cx32c__dcc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__sym__16x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__sym__16x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__32cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__sym__32cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__32cx32__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__sym__32cx32c__dcc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__sym__32x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__sym__32x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__ct__16cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__sym__ct__16cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__ct__16cx32__dcn.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__sym__ct__16x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__sym__ct__16x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__ct__32cx16__dcn.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__ct__32cx32__dcn.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__sym__ct__32x16c__dnc.html',1,'']]],
  ['dynamic_20z_20buffer_20conjugation',['Dynamic Z buffer conjugation',['../group__vect__mult__sym__ct__32x32c__dnc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__uct__16cx16__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__sym__uct__16cx16c__dcc.html',1,'']]],
  ['dynamic_20x_20buffer_20conjugation',['Dynamic X buffer conjugation',['../group__vect__mult__sym__uct__16cx32__dcn.html',1,'']]],
  ['dynamic_20x_20and_20z_20buffer_20conjugation',['Dynamic X and Z buffer conjugation',['../group__vect__mult__sym__uct__16cx32c__dcc.html',1,'']]]
];
