var searchData=
[
  ['vector_20data_2dtypes',['Vector Data-types',['../group__dt__gpvector.html',1,'']]],
  ['vector_20conversions',['Vector Conversions',['../group__intr__gpvectorconv.html',1,'']]],
  ['vector_20operations',['Vector Operations',['../group__intr__gpvectorop.html',1,'']]],
  ['vector_20arithmetic',['Vector Arithmetic',['../group__intr__gpvectorop__arithmetic.html',1,'']]],
  ['vector_20comparison',['Vector comparison',['../group__intr__gpvectorop__comparison.html',1,'']]],
  ['vector_20maxdiff',['Vector MaxDiff',['../group__intr__gpvectorop__mdiff__cmp.html',1,'']]],
  ['vector_20compares',['Vector Compares',['../group__intr__gpvectorop__vec__cmp.html',1,'']]],
  ['vector_20lane_20selection',['Vector Lane Selection',['../group__intr__gpvectorop__vec__sel.html',1,'']]],
  ['vector_20max_2fmin',['Vector Max/Min',['../group__intr__gpvectorop__word__cmp__max__min.html',1,'']]],
  ['v16accfloat',['v16accfloat',['../group__dt__fpoint__acc.html#ga7c5ee5a24fb49d94b12474a8a576ff00',1,'me_chess.h']]],
  ['v16caccfloat',['v16caccfloat',['../group__dt__fpoint__acc.html#gaee9fb08f985e2232b713fb6725409d1b',1,'me_chess.h']]],
  ['v2caccfloat',['v2caccfloat',['../group__dt__fpoint__acc.html#ga3db732a75a78de23aa13dbd455ae711e',1,'me_chess.h']]],
  ['v32accfloat',['v32accfloat',['../group__dt__fpoint__acc.html#gab1c824a4701e0ce83e0c02bf7435ce4e',1,'me_chess.h']]],
  ['v4accfloat',['v4accfloat',['../group__dt__fpoint__acc.html#ga8db24cc7cc270c92d010ddfdc06d8a1a',1,'me_chess.h']]],
  ['v4caccfloat',['v4caccfloat',['../group__dt__fpoint__acc.html#gab3d29cfa459cac84dc2eb3e0408a863c',1,'me_chess.h']]],
  ['v8accfloat',['v8accfloat',['../group__dt__fpoint__acc.html#gac5860d57e6112f9bcefb22127ef0e498',1,'me_chess.h']]],
  ['v8caccfloat',['v8caccfloat',['../group__dt__fpoint__acc.html#ga33d83700f50b34ea8aa46248c87f1b32',1,'me_chess.h']]],
  ['vector_20mac',['Vector MAC',['../group__vect__mult.html',1,'']]],
  ['vector_20mac_20with_20pre_2dsubtraction',['Vector MAC with pre-subtraction',['../group__vect__mult__antisym.html',1,'']]],
  ['vector_20mac_20with_20partial_20pre_2dsubtraction',['Vector MAC with partial pre-subtraction',['../group__vect__mult__antisym__ct.html',1,'']]],
  ['vector_20mac_20with_20pre_2dsubtraction_20and_20upshifting',['Vector MAC with pre-subtraction and upshifting',['../group__vect__mult__antisym__uct.html',1,'']]],
  ['vector_20mac_20combined_20with_20vector_20comparisons',['Vector MAC combined with vector comparisons',['../group__vect__mult__cmp.html',1,'']]],
  ['vector_20mac_20with_20pre_2dsubtraction_20and_20conjugation',['Vector MAC with pre-subtraction and conjugation',['../group__vect__mult__conj__antisym.html',1,'']]],
  ['vector_20mac_20with_20pre_2dadding_20and_20conjugation',['Vector MAC with pre-adding and conjugation',['../group__vect__mult__conj__sym.html',1,'']]],
  ['vector_20mac_20with_20pre_2dadding',['Vector MAC with pre-adding',['../group__vect__mult__sym.html',1,'']]],
  ['vector_20mac_20with_20partial_20pre_2dadding',['Vector MAC with partial pre-adding',['../group__vect__mult__sym__ct.html',1,'']]],
  ['vector_20mac_20with_20pre_2dadding_20and_20upshifting',['Vector MAC with pre-adding and upshifting',['../group__vect__mult__sym__uct.html',1,'']]]
];
